"""seguranca: conta, 2fa, avatar, lockout, revogacao

Revision ID: 1b67b813c3e5
Revises: adb4aee44d2d
Create Date: 2026-07-17 11:08:13.073997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b67b813c3e5'
down_revision: Union[str, None] = 'adb4aee44d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditoria_evento', sa.Column('ator_matricula', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_auditoria_evento_ator_matricula'), 'auditoria_evento', ['ator_matricula'], unique=False)
    op.add_column('usuario', sa.Column('email', sa.String(length=160), nullable=True))
    op.add_column('usuario', sa.Column('telefone', sa.String(length=30), nullable=True))
    op.add_column('usuario', sa.Column('avatar_url', sa.String(length=300), nullable=True))
    op.add_column('usuario', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('usuario', sa.Column('totp_ativado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('usuario', sa.Column('trocar_senha_no_proximo_login', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('usuario', sa.Column('tentativas_falhas', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('usuario', sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario', sa.Column('sessao_revogada_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'sessao_revogada_em')
    op.drop_column('usuario', 'bloqueado_ate')
    op.drop_column('usuario', 'tentativas_falhas')
    op.drop_column('usuario', 'trocar_senha_no_proximo_login')
    op.drop_column('usuario', 'totp_ativado')
    op.drop_column('usuario', 'totp_secret')
    op.drop_column('usuario', 'avatar_url')
    op.drop_column('usuario', 'telefone')
    op.drop_column('usuario', 'email')
    op.drop_index(op.f('ix_auditoria_evento_ator_matricula'), table_name='auditoria_evento')
    op.drop_column('auditoria_evento', 'ator_matricula')
    # ### end Alembic commands ###
