"""schema inicial: fundo, periodo, ativo, estrategia SCD2, contribuicao, serie, var, benchmark

Revision ID: 3c64c2848414
Revises: 
Create Date: 2026-07-14 16:31:41.898523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c64c2848414'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fundo',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=40), nullable=False),
    sa.Column('classe', sa.String(length=100), nullable=False),
    sa.Column('benchmark_padrao', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('estrategia_versao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_codigo', sa.String(length=20), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('nome_estrategia', sa.String(length=120), nullable=False),
    sa.Column('dt_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('dt_fim_vigencia', sa.Date(), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('matricula_responsavel', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['fundo_codigo'], ['fundo.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_estrategia_versao_vigente', 'estrategia_versao', ['fundo_codigo', 'ativo_id'], unique=True, postgresql_where=sa.text('vigente = true'))
    op.create_table('periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_codigo', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fundo_codigo'], ['fundo.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundo_codigo', 'label', name='uq_periodo_fundo_label')
    )
    op.create_table('var_classe_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_codigo', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('classe', sa.Enum('JUROS', 'INFLACAO', 'CREDITO', 'EQUITY', 'FX', 'COMMODITY', 'TOTAL', name='classe_var_enum'), nullable=False),
    sa.Column('valor_pct_nav', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fundo_codigo'], ['fundo.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundo_codigo', 'data', 'classe', name='uq_var_dia_classe')
    )
    op.create_table('benchmark_peso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_codigo', sa.String(length=20), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('dt_versao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.ForeignKeyConstraint(['fundo_codigo'], ['fundo.codigo'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribuicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_codigo', sa.String(length=20), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('dimensao', sa.Enum('ESTRATEGIA', 'GRUPO_CONTABIL', 'SUPERGRUPO', 'PRIVADOS', 'RENDA_VARIAVEL', 'RENDA_FIXA', 'VENCIMENTO', 'ATIVOS', name='dimensao_enum'), nullable=False),
    sa.Column('chave_dimensao', sa.String(length=120), nullable=False),
    sa.Column('contribuicao_pp', sa.Float(), nullable=False),
    sa.Column('peso_medio', sa.Float(), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fundo_codigo'], ['fundo.codigo'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_alteracao_estrategia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrategia_versao_id', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('tipo_alteracao', sa.String(length=20), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estrategia_versao_id'], ['estrategia_versao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundo_codigo', sa.String(length=20), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cota', sa.Float(), nullable=False),
    sa.Column('bench', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fundo_codigo'], ['fundo.codigo'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundo_codigo', 'periodo_id', 'data', name='uq_serie_dia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie_diaria')
    op.drop_table('log_alteracao_estrategia')
    op.drop_table('contribuicao')
    op.drop_table('benchmark_peso')
    op.drop_table('var_classe_diaria')
    op.drop_table('periodo')
    op.drop_index('uq_estrategia_versao_vigente', table_name='estrategia_versao', postgresql_where=sa.text('vigente = true'))
    op.drop_table('estrategia_versao')
    op.drop_table('fundo')
    op.drop_table('benchmark')
    op.drop_table('ativo')
    # ### end Alembic commands ###
