"""meta4: gestora, usuario, papel, fundo.gestora_id

Revision ID: 5d85c44c0d51
Revises: 3c64c2848414
Create Date: 2026-07-14 21:22:55.584081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d85c44c0d51'
down_revision: Union[str, None] = '3c64c2848414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.Enum('ANALISTA', 'GESTOR', 'COMPLIANCE', name='papel_enum'), nullable=False),
    sa.Column('gestora_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gestora_id'], ['gestora.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.add_column('fundo', sa.Column('gestora_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fundo', 'gestora', ['gestora_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fundo', type_='foreignkey')
    op.drop_column('fundo', 'gestora_id')
    op.drop_table('usuario')
    op.drop_table('gestora')
    # ### end Alembic commands ###
