"""cadastro: status_cadastro, convite_token, convite_expira_em

Revision ID: 6350f4a6ba31
Revises: 1b67b813c3e5
Create Date: 2026-07-17 20:01:38.352389

NOTA (achado #9, plano 008, 2026-07-21): a constraint de `convite_token`
foi nomeada explicitamente aqui (`uq_usuario_convite_token`) porque o
`downgrade()` original usava `op.drop_constraint(None, ...)`, que é
inexecutável (Alembic exige nome real). Em qualquer banco onde esta
migration já rodou ANTES desta correção, o Postgres deu um nome
autogerado à constraint (`usuario_convite_token_key`) — rode
`ALTER TABLE usuario RENAME CONSTRAINT usuario_convite_token_key TO uq_usuario_convite_token;`
nesse banco antes de tentar `alembic downgrade` (já aplicado nos bancos
`prisma`/`prisma_test` de dev desta sessão — produção ainda pendente,
aplicar no próximo deploy).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6350f4a6ba31'
down_revision: Union[str, None] = '1b67b813c3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `add_column` numa tabela existente não cria o tipo Postgres sozinho
    # (diferente de `create_table`, que cria o ENUM implicitamente) — precisa
    # do CREATE TYPE explícito antes.
    status_cadastro_enum = sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='status_cadastro_enum')
    status_cadastro_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('usuario', sa.Column('status_cadastro', status_cadastro_enum, server_default=sa.text("'APROVADO'"), nullable=False))
    op.add_column('usuario', sa.Column('convite_token', sa.String(length=64), nullable=True))
    op.add_column('usuario', sa.Column('convite_expira_em', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint("uq_usuario_convite_token", "usuario", ["convite_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_usuario_convite_token", "usuario", type_="unique")
    op.drop_column('usuario', 'convite_expira_em')
    op.drop_column('usuario', 'convite_token')
    op.drop_column('usuario', 'status_cadastro')
    sa.Enum(name='status_cadastro_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
