"""meta4: auditoria_evento

Revision ID: adb4aee44d2d
Revises: 5d85c44c0d51
Create Date: 2026-07-14 21:35:47.491580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb4aee44d2d'
down_revision: Union[str, None] = '5d85c44c0d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rota', sa.String(length=60), nullable=False),
    sa.Column('fundo', sa.String(length=20), nullable=False),
    sa.Column('pergunta', sa.String(), nullable=False),
    sa.Column('backend', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('fontes_json', sa.String(), nullable=False),
    sa.Column('bloqueados_json', sa.String(), nullable=False),
    sa.Column('resposta_hash', sa.String(length=16), nullable=False),
    sa.Column('extra_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria_evento')
    # ### end Alembic commands ###
