"""matricula unica por gestora, nao global

Revision ID: da37183b664a
Revises: b771e5c3af76
Create Date: 2026-07-21 00:39:35.722532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da37183b664a'
down_revision: Union[str, None] = 'b771e5c3af76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuario_matricula_key', 'usuario', type_='unique')
    op.create_unique_constraint('uq_usuario_gestora_matricula', 'usuario', ['gestora_id', 'matricula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ATENÇÃO: se já existirem duas linhas com a mesma matrícula em
    # gestoras diferentes quando este downgrade rodar, ele vai falhar
    # (viola a constraint global que está sendo recriada) — esperado, não
    # um bug da migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuario_gestora_matricula', 'usuario', type_='unique')
    op.create_unique_constraint('usuario_matricula_key', 'usuario', ['matricula'])
    # ### end Alembic commands ###
